destination: ./_site
auto:        false
lsi:         false
pygments:    true
markdown:    maruku
permalink:   date
maruku:
  use_tex:   false
  use_divs:  false
  png_dir:   images/latex
  png_url:   /images/latex